# Generated by Django 5.0.2 on 2024-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('star_rating', models.FloatField(default=0)),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('establishment_name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('ai_script', models.TextField(blank=True, default='')),
                ('reviews', models.ManyToManyField(blank=True, to='kritikApp.review')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('bookmarks', models.ManyToManyField(blank=True, to='kritikApp.establishment')),
                ('reviews', models.ManyToManyField(blank=True, to='kritikApp.review')),
            ],
        ),
    ]
