# Generated by Django 5.0.2 on 2024-03-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritikApp', '0002_alter_establishment_ai_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kritikApp.establishment'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kritikApp.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='establishment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
